version: '2'
services:
  wildfly:
    build:
        context: ../
        dockerfile: images/wildfly/Dockerfile
    links:
    - mysql:db
    ports:
     - "9091:8080"
     - "9991:9990"
  mysql:
    build: ../images/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=adminpw
    ports:
    - "3307:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
    - MYSQL_ROOT_PASSWORD=adminpw
    ports:
    - "6060:80"
    links:
    - mysql:db